api_version = "2024-04"

[[extensions]]
type = "function"
name = "SiGNL Bundle Discount"
handle = "bundle-discount"
function_type = "product_discounts"

[extensions.build]
command = "npm run build"
path = "dist/index.wasm"
watch_paths = ["src/index.js"]
